server:
  port: 8180
# 开发环境配置
spring:
    profiles:
        active: dev
    data:
        hbase:
            quorum: 192.168.10.212:2181,192.168.10.216,192.168.10.219
            rootDir: hdfs://192.168.10.212:9000
            nodeParent: /hbase


